---
title: "Using Git and GitHub"
subtitle: "💪"
author: "Tyson S. Barrett"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

class: inverse

# Outline

--

## What is Git?

--

## What is GitHub?

--

## Why Use 'em??

--

## Getting Started

---

# References




---
class: inverse, middle, center
# Git
---

# Git

Git is a version control system

- It works with plain text files (like Rmd)
- Looks for changes in the file and keeps track of the changes
- Allows you to see changes over time and return to previous versions

---
class: inverse, middle, center
# GitHub

---
# GitHub

One of the online portals of Git.

## Repositories

A collection of files and folders (generally within a single project).




---
class: inverse, middle, center

# Why Use 'em??

---


---
class: inverse, middle, center

# Getting Started

---

# Install Git

[https://git-scm.com/book/en/v2/Getting-Started-Installing-Git](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git)

---

# Get a GitHub Account

## [github.com](https://www.github.com)

A free account let's you do most things

- No private repositories though


---
# Final Note

## OSF
A new, free resource that incorporates GitHub, Dropbox, and other cool features

### [osf.io](https://osf.io)